server:
 port: 8083
 servlet:
    context-path: /

spring:
  dubbo:
    application:
      name: caimao-devops
    registry:
      address: zookeeper://192.168.1.190
      port: 2181
    scan: com.springboot.dubboTest.controller